# .. Copyright (C) 2012-2016 Bryan A. Jones.
#
#    This file is part of CodeChat.
#
#    CodeChat is free software: you can redistribute it and/or modify it under
#    the terms of the GNU General Public License as published by the Free
#    Software Foundation, either version 3 of the License, or (at your option)
#    any later version.
#
#    CodeChat is distributed in the hope that it will be useful, but WITHOUT ANY
#    WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#    FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
#    details.
#
#    You should have received a copy of the GNU General Public License along
#    with CodeChat.  If not, see <http://www.gnu.org/licenses/>.
#
# *************************************
# .travis.yml - Travis CI configuration
# *************************************
# .. highlight:: yaml
#
# See https://docs.travis-ci.com/user/multi-os/.
os: linux
# See https://docs.travis-ci.com/user/languages/python.
language: python
python:
  - 3.6
  - 3.5
  - 3.4

# See https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix. This
# manually includes additional OS X tests to the matrix of Linux tests defined
# above.
matrix:
  include:
  - os: osx
    # Since OS X doesn't natively support Python, use some workarounds (see
    # before_install_ for details).
    language: generic
    # See https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-.travis.yml.
    env: INSTALL_TYPE=macpython VERSION=3.6 VENV=venv
  - os: osx
    language: generic
    env: INSTALL_TYPE=macpython VERSION=3.5 VENV=venv
  - os: osx
    language: generic
    env: INSTALL_TYPE=macpython VERSION=3.4 VENV=venv

# _`before_install`: Perform the manual steps on OS X to install python3 and
# activate venv, since Python support is not available, per the list of
# `unsupported languages on OS X <https://github.com/travis-ci/travis-ci/issues/2320>`_.
# The following approach is based on a `workaround <https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-195620855>`_.
# This was modified based on `instructions to install multiple Python versions on OS X <https://gist.github.com/Bouke/11261620>`_.
# See also the `pyenv docs <https://github.com/yyuu/pyenv/blob/master/README.md>`_.
before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    git clone https://github.com/MacPython/terryfy.git
    # Avoid printing the lines from the script below.
    source terryfy/travis_tools.sh
    get_python_environment $INSTALL_TYPE $VERSION $VENV
  fi

install:
  # Make sure we're using the latest version of pip. Use the approach which
  # `Appveyor requires <Appveyor pip install>`_ to keep the CI files as close
  # as possible.
  - python -m pip install -U pip

  # See :ref:`here <Appveyor pip install command>`.
  - pip install -e .[test]

# Run the tests.
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source terryfy/test_tools.sh; fi
  # On OS X, ``py.test`` with no parameters runs all CodeChat tests, then
  # discovers others that fail. Try to avoid this. Also, invoking ``py.test``
  # refers to the system Python. So, run it as a module to use the selected
  # Python 3 version.
  - python -m pytest ./test
